In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)  # eyni nəticə üçün

n = 20  # sətir sayı

data = {
    "buying": np.random.choice(["low", "med", "high", "vhigh"], n),
    "maint": np.random.choice(["low", "med", "high", "vhigh"], n),
    "doors": np.random.choice(["2", "3", "4", "5more"], n),
    "persons": np.random.choice(["2", "4", "more"], n),
    "lug_boot": np.random.choice(["small", "med", "big"], n),
    "safety": np.random.choice(["low", "med", "high"], n),
    "class": np.random.choice(["unacc", "acc", "good", "vgood"], n)
}

df = pd.DataFrame(data)

df

   buying  maint  doors persons lug_boot safety  class
0    high    med      4    more    small    low   good
1   vhigh    low      4    more      med    med   good
2     low    med      3       2      med    low  unacc
3    high  vhigh  5more       2      med    low  vgood
4    high  vhigh  5more    more      med    med   good
5   vhigh    med  5more       4      med   high   good
6     low    med  5more       2      med    low  unacc
7     low    med      4       4      med    med   good
8    high  vhigh      3       4    small    low  unacc
9     med  vhigh      3       4      big    low    acc
10   high    low      4       2      med    low   good
11   high    low      3       4      med    low    acc
12   high  vhigh      4       2      med   high  unacc
13   high    med  5more       4      med    low  vgood
14  vhigh    med      4    more      med    low   good
15    low    low  5more    more      med    low  unacc
16  vhigh  vhigh  5more       2      big   high  vgood
17  vhigh    low      2    more      big    low  vgood
18  vhigh    low      4    more      med    low    acc
19   high   high      2       4      big   high  unacc

In [2]:
map_buying = {
    "low": 0,   
    "med": 1,
    "high": 2,
    "vhigh": 3
}
df['buying'] = df['buying'].map(map_buying)
df

    buying  maint  doors persons lug_boot safety  class
0        2    med      4    more    small    low   good
1        3    low      4    more      med    med   good
2        0    med      3       2      med    low  unacc
3        2  vhigh  5more       2      med    low  vgood
4        2  vhigh  5more    more      med    med   good
5        3    med  5more       4      med   high   good
6        0    med  5more       2      med    low  unacc
7        0    med      4       4      med    med   good
8        2  vhigh      3       4    small    low  unacc
9        1  vhigh      3       4      big    low    acc
10       2    low      4       2      med    low   good
11       2    low      3       4      med    low    acc
12       2  vhigh      4       2      med   high  unacc
13       2    med  5more       4      med    low  vgood
14       3    med      4    more      med    low   good
15       0    low  5more    more      med    low  unacc
16       3  vhigh  5more       2      big   high  vgood
17       3    low      2    more      big    low  vgood
18       3    low      4    more      med    low    acc
19       2   high      2       4      big   high  unacc

In [3]:
df["buying"].unique()

array([2, 3, 0, 1])

In [4]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
df['buying']= label_encoder.fit_transform(df["buying"])
df["maint"] = label_encoder.fit_transform(df["maint"])

In [8]:
df["maint"] = label_encoder.fit_transform(df["maint"])

In [12]:
df["maint"] = label_encoder.fit_transform(df["maint"])
df

    buying  maint  doors persons lug_boot safety  class
0        2      2      4    more    small    low   good
1        3      1      4    more      med    med   good
2        0      2      3       2      med    low  unacc
3        2      3  5more       2      med    low  vgood
4        2      3  5more    more      med    med   good
5        3      2  5more       4      med   high   good
6        0      2  5more       2      med    low  unacc
7        0      2      4       4      med    med   good
8        2      3      3       4    small    low  unacc
9        1      3      3       4      big    low    acc
10       2      1      4       2      med    low   good
11       2      1      3       4      med    low    acc
12       2      3      4       2      med   high  unacc
13       2      2  5more       4      med    low  vgood
14       3      2      4    more      med    low   good
15       0      1  5more    more      med    low  unacc
16       3      3  5more       2      big   high  vgood
17       3      1      2    more      big    low  vgood
18       3      1      4    more      med    low    acc
19       2      0      2       4      big   high  unacc

In [ ]:
df_encoded = pd.apply(lambda enc: label_encoder.fit_transform(enc.astype(str)))
df_encoded

TypeError: LabelEncoder() takes no arguments

In [10]:
df["maint"] = label_encoder.fit_transform(df["maint"])

In [11]:
df

    buying  maint  doors persons lug_boot safety  class
0        2      2      4    more    small    low   good
1        3      1      4    more      med    med   good
2        0      2      3       2      med    low  unacc
3        2      3  5more       2      med    low  vgood
4        2      3  5more    more      med    med   good
5        3      2  5more       4      med   high   good
6        0      2  5more       2      med    low  unacc
7        0      2      4       4      med    med   good
8        2      3      3       4    small    low  unacc
9        1      3      3       4      big    low    acc
10       2      1      4       2      med    low   good
11       2      1      3       4      med    low    acc
12       2      3      4       2      med   high  unacc
13       2      2  5more       4      med    low  vgood
14       3      2      4    more      med    low   good
15       0      1  5more    more      med    low  unacc
16       3      3  5more       2      big   high  vgood
17       3      1      2    more      big    low  vgood
18       3      1      4    more      med    low    acc
19       2      0      2       4      big   high  unacc

In [ ]:
label